//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolashaqWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KruzhokPictures
    {
        public int ID { get; set; }
        public int KruzhokID { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Kruzhok Kruzhok { get; set; }
    }
}
