//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolashaqWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BolashaqDBEntities : DbContext
    {
        public BolashaqDBEntities()
            : base("name=BolashaqDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeClasses> AgeClasses { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Kruzhok> Kruzhok { get; set; }
        public virtual DbSet<Lgots> Lgots { get; set; }
        public virtual DbSet<MethodistOtdels> MethodistOtdels { get; set; }
        public virtual DbSet<Otdels> Otdels { get; set; }
        public virtual DbSet<Poseshenie> Poseshenie { get; set; }
        public virtual DbSet<PoseshenieStatuses> PoseshenieStatuses { get; set; }
        public virtual DbSet<StudentLgots> StudentLgots { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<ZayavkaStatuses> ZayavkaStatuses { get; set; }
        public virtual DbSet<KruzhokPictures> KruzhokPictures { get; set; }
    }
}
