//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BolashaqWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Poseshenie = new HashSet<Poseshenie>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public byte GenderID { get; set; }
        public string Nationality { get; set; }
        public string IIN { get; set; }
        public string IDNumber { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string S027Number { get; set; }
        public byte[] ParentDoc { get; set; }
    
        public virtual Genders Genders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poseshenie> Poseshenie { get; set; }
        public virtual StudentLgots StudentLgots { get; set; }
        public virtual Users Users { get; set; }
    }
}
